# Volume and Media Control
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5 
bind = , XF86AudioLowerVolume, exec, pamixer -d 5 
bind = , XF86AudioMicMute, exec, pamixer --default-source -m
bind = , XF86AudioMute, exec, pamixer -t
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

# Screen brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

# Applications
bind = Super, Return, exec, kitty
bind = Super, E, exec, thunar

# App Launcher
bind = Super, F, exec, pkill wofi || wofi -IS drun

# Screenshot, Clipboard
bind = , Print, exec, grim -g "$(slurp)" - | swappy -f -
bind = Super, Print, exec, grim - | swappy -f -
bind = Super, V, exec, pkill wofi || cliphist list | wofi -S dmenu | cliphist decode | wl-copy
