# Windowrule
windowrulev2 = workspace 1, class:^([Ff]irefox)$
windowrulev2 = workspace 2, class:^([Tt]hunar)$
windowrulev2 = workspace 3, class:^(com.obsproject.Studio)$
windowrulev2 = workspace 4, class:^([Ss]team)$
windowrulev2 = workspace 5, class:^([Dd]iscord|[Vv]esktop)$
windowrulev2 = workspace 6, class:^([Ss]potify)$

# Screen Tearing
windowrulev2 = immediate, class:^([Ss]team)$
windowrulev2 = immediate, class:^(dota2)$

# Floating
windowrulev2 = float, class:(xdg-desktop-portal-gtk)
windowrulev2 = float, class:([Tt]hunar), title:(File Operation Progress)
windowrulev2 = float, class:([Tt]hunar), title:(Confirm to replace files)
windowrulev2 = float, class:(org.gnome.Calculator), title:(Calculator)
windowrulev2 = float, class:^(eog)$
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(nwg-look|qt5ct|qt6ct)$
windowrulev2 = float, class:^(nm-applet|nm-connection-editor|blueman-manager)$
windowrulev2 = float, class:^(file-roller|org.gnome.FileRoller)$
windowrulev2 = float, title:(Kvantum Manager)

# Move Window
windowrulev2 = move 25% 25%, class:^(pavucontrol)$

# Window Size
windowrulev2 = size 70% 70%, class:^(xdg-desktop-portal-gtk)$
windowrulev2 = size 50% 50%, title:(Kvantum Manager)
windowrulev2 = size 60% 70%, class:^(nwg-look|qt5ct|qt6ct|)$
windowrulev2 = size 50% 50%, class:^(file-roller|org.gnome.FileRoller)$

# Firefox Stuff
windowrulev2 = opacity 0.95 0.75, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = size 25% 25%, title:^(Picture-in-Picture)$
windowrulev2 = move 73% 73%, title:^(Picture-in-Picture)$

# Screen Sharing
windowrulev2 = opacity 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2 = noblur,class:^(xwaylandvideobridge)$
