# XDG stuff
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Start Polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Applications
exec-once = uwsm app -- waybar
exec-once = uwsm app -- nm-applet --indicator
exec-once = uwsm app -- dunst
exec-once = uwsm app -- udiskie
#exec-once = uwsm app -- blueman-applet

# Clipboard
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

# hypridle
exec-once = uwsm app -- hypridle

# wallpaper
exec-once = uwsm app -- waypaper --restore
