# Window Tags

## Browsers
windowrulev2 = tag +browser, class:^([Ff]irefox)$
windowrulev2 = tag +browser, class:^([Zz]en)$

## Email
windowrulev2 = tag +email, class:^(org.mozilla.[Tt]hunderbird)$

## File Managers
windowrulev2 = tag +filemanager, class:^([Tt]hunar)$

## Screen Recording
windowrulev2 = tag +screenrecord, class:^(com.obsproject.Studio)$

## Game Store
windowrulev2 = tag +gamestore, class:^(net.lutris.Lutris)$
windowrulev2 = tag +gamestore, class:^([Ss]team)$

## Virtual Machines
windowrulev2 = tag +vm, class:^(virt-manager)$
windowrulev2 = tag +vm, class:^([Vv][Mm]ware)$
windowrulev2 = tag +vm, class:^([Vv]irtual[Bb]ox [Mm]anager)$

## Instant Messaging
windowrulev2 = tag +im, class:^(io.github.kukuruzka165.materialgram)$
windowrulev2 = tag +im, class:^([Vv]esktop)$
windowrulev2 = tag +im, class:^(com.rtosta.zapzap)$
windowrulev2 = tag +im, class:^([Zz]oom)$

## Games
windowrulev2 = tag +game, class:^(gamescope)$
windowrulev2 = tag +game, class:^(steam_app_\d+)$

## Multimedia
windowrulev2 = tag +multimedia, class:^([Ss]potify)$

# Move to Workspace
windowrulev2 = workspace 1, tag:browser*
windowrulev2 = workspace 2, tag:email* 
windowrulev2 = workspace 3, tag:filemanager*
windowrulev2 = workspace 4, tag:screenrecord*
windowrulev2 = workspace 5, tag:gamestore* 
windowrulev2 = workspace 6, tag:vm*
windowrulev2 = workspace 7, tag:im* 
windowrulev2 = workspace 8, tag:game* 
windowrulev2 = workspace 9, tag:multimedia*

# Floating window
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(org.gnome.Calculator)
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = float, class:^([Ss]team)$, title:^((?![Ss]team).*|[Ss]team [Ss]ettings)$
windowrulev2 = float, class:^([Vv]irtual[Bb]ox)$, title:^((.*?[Ss]ettings))$

# Position
windowrulev2 = center, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = center, class:^(blueman-manager)$
windowrulev2 = center, class:^(nm-connection-editor)$
windowrulev2 = center, class:^(org.gnome.Calculator)$
windowrulev2 = center, class:^([Vv]irtual[Bb]ox)$, title:^((.*?[Ss]ettings))$
windowrulev2 = move 69.5% 4%, title:^(Picture-in-Picture)$

# Sizes
windowrulev2 = size 700 600, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = size 700 600, class:^(blueman-manager)$
windowrulev2 = size 700 600, class:^(nm-connection-editor)$
windowrulev2 = size 700 600, class:^(org.gnome.Calculator)$
windowrulev2 = size 960 640, class:^([Vv]irtual[Bb]ox)$, title:^((.*?[Ss]ettings))$

# Window Pinning
windowrulev2 = pin, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = pin, title:^(Picture-in-Picture)$

# Idle inhibit fullscreen apps
windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1

# common modals
windowrule = float, title:^(Open)$
windowrule = float, title:^(Choose Files)$
windowrule = float, title:^(Save As)$
windowrule = float, title:^(Confirm to replace files)$
windowrule = float, title:^(File Operation Progress)$
