$main = $HOME/.config/hypr/main
$keybinds = $HOME/.config/hypr/keybinds

# Main Configurations
source = $main/autostart.conf
source = $main/layouts.conf
source = $main/monitor.conf
source = $main/rules.conf
source = $main/variables.conf

# Keybinds 
source = $keybinds/global.conf
source = $keybinds/user.conf
