input {
  kb_layout=us
  numlock_by_default=true
  repeat_rate=35
  repeat_delay=250
  follow_mouse=1

  touchpad {
    disable_while_typing=true
    natural_scroll=true
    clickfinger_behavior=true
  }
}

binds {
  scroll_event_delay = 0
}

gestures {
  workspace_swipe=true
  workspace_swipe_use_r=true
}
