# Modifier Key
$mainMod = SUPER

# Basics
bind = $mainMod, Return, exec, kitty 
bind = $mainMod, F, exec, pkill wofi || wofi
bind = $mainMod, E, exec, thunar 

bind = $mainMod, Q, killactive
bind = $mainMod+Shift, Space, togglefloating

# Volume
bindl = , XF86AudioMute, exec, pamixer -t
bindle = , XF86AudioRaiseVolume, exec, pamixer -ui 5
bindle = , XF86AudioLowerVolume, exec, pamixer -ud 5

# Player
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindle = , XF86AudioNext, exec, playerctl next
bindle = , XF86AudioPrev, exec, playerctl previous

# Brightness
bindle = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bindle = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

# Screenshot
bind = , Print, exec, grimblast -w 1 save area - | swappy -f -
bind = $mainMod, Print, exec, grimblast save screen - | swappy -f -
bind = $mainMod+Shift, Print, exec, grimblast save active - | swappy -f - 

# Clipboard
bind = $mainMod, V, exec, pkill wofi || cliphist list | wofi -S dmenu | cliphist decode | wl-copy

# Move Focus
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Swap Window
bind = $mainMod+Shift, left, movewindow, l
bind = $mainMod+Shift, right, movewindow, r
bind = $mainMod+Shift, up, movewindow, u
bind = $mainMod+Shift, down, movewindow, d

# Switch workspaces with mainMod + [0-9]
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = Super SHIFT, 1, movetoworkspace, 1
bind = Super SHIFT, 2, movetoworkspace, 2
bind = Super SHIFT, 3, movetoworkspace, 3
bind = Super SHIFT, 4, movetoworkspace, 4
bind = Super SHIFT, 5, movetoworkspace, 5
bind = Super SHIFT, 6, movetoworkspace, 6
bind = Super SHIFT, 7, movetoworkspace, 7
bind = Super SHIFT, 8, movetoworkspace, 8
bind = Super SHIFT, 9, movetoworkspace, 9
bind = Super SHIFT, 0, movetoworkspace, 10

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow
