[colors]
bg          =   #282a36
fg          =   #f8f8f2
selection   =   #44475a
comment     =   #6272A4

cyan        =   #8BE9FD
green       =   #50fa7b
orange      =   #ffb86c
pink        =   #ff79c6
purple      =   #bd93f9
red         =   #ff5555
yellow      =   #f1fa8c

bg-light    =   #343746
bg-dark     =   #21222C

[bar/main]
width           =   100%
height          =   30
line-size       =   2
offset-y        =   0
bottom          =   true
fixed-center    =   true

scroll-up = next
scroll-down = prev

enable-ipc = true

wm-restack      =   i3

background      =   ${colors.bg}
foreground      =   ${colors.fg}

override-redirect = false

font-0  =   "JetBrainsMono Nerd Font:pixelsize=10;0"

modules-left    =   date margin pulseaudio margin backlight
modules-center  =   i3
modules-right   =   filesystem margin memory margin cpu margin battery margin session margin

tray-background =   ${colors.bg}
tray-position   =   right
tray-maxsize    =   16

cursor-click    = pointer
cursor-scroll   = ns-resize


[settings]
screenchange-reload = true

[module/i3]
type            =   internal/i3
index-sort      =   true
strip-wsnumbers = true

ws-icon-0       =   "1;"
ws-icon-1       =   "2;"
ws-icon-2       =   "3;"
ws-icon-3       =   "4;"
ws-icon-4       =   "5;ﭮ"
ws-icon-5       =   "6;6"
ws-icon-6       =   "7;7"
ws-icon-7       =   "8;8"
ws-icon-8       =   "9;9"
ws-icon-9      =   "10;10"

format          =   <label-state> <label-mode>

label-mode-foreground   =   ${colors.purple}
label-mode-padding      =   1

label-focused               =   %icon%
label-focused-underline     =   ${colors.green}
label-focused-padding       =   1

; unfocused = Inactive workspace on any monitor
label-unfocused             =   %icon%
label-unfocused-padding     =   1
; label-unfocused-underline   =   ${colors.purple}

; visible = Active workspace on unfocused monitor
label-visible               =   %icon%
label-visible-background    =   ${colors.comment}
label-visible-padding       =   1

; urgent = Workspace with urgency hint set
label-urgent            =   %icon%
label-urgent-background =   ${colors.red}
label-urgent-padding    =   1

[module/date]
type        =   internal/date
interval    =   1

time        =    "%H:%M"
time-alt    =    "%A, %d %b %Y %H:%M:%S"

format                      =   <label>
format-prefix               =   ""
format-prefix-background    =   ${colors.green}
format-prefix-foreground    =   ${colors.bg}
format-prefix-padding       =   1
format-underline            =   ${colors.green}

label               =   %{T1}%time%%{T-}
label-background    =   ${colors.bg-light}
label-foreground    =   ${colors.fg}
label-padding       =   1

[module/pulseaudio]
type    =   internal/pulseaudio

format-volume                   =   <label-volume>
format-volume-prefix            =   "墳"
format-volume-prefix-background =   ${colors.orange}
format-volume-prefix-foreground =   ${colors.bg}
format-volume-prefix-padding    =   1
format-volume-underline         =   ${colors.orange}

label-volume            =   %{T1}%percentage%%%{T-}
label-volume-background =   ${colors.bg-light}
label-volume-foreground =   ${colors.fg}
label-volume-padding    =   1

format-muted                    =   <label-muted>
format-muted-prefix             =   "ﱝ"
format-muted-prefix-background  =   ${colors.red}
format-muted-prefix-foreground  =   ${colors.bg}
format-muted-prefix-padding     =   1
format-muted-underline          =   ${colors.red}

label-muted             =   %{T1}%percentage%%%{T-}
label-muted-background  =   ${colors.bg-light}
label-muted-foreground  =   ${colors.fg}
label-muted-padding     =   1

click-right     =   pavucontrol &

[module/backlight]
type    =   internal/backlight
card    =   intel_backlight

use-actual-brightness   =   true
enable-scroll           =   true

format                      =   <label>
format-prefix               =   ""
format-prefix-background    =   ${colors.yellow}
format-prefix-foreground    =   ${colors.bg}
format-prefix-padding       =   1
format-underline            =   ${colors.yellow}

label               =   %{T1}%percentage%%%{T-}
label-background    =   ${colors.bg-light}
label-foreground    =   ${colors.fg}
label-padding       =   1

[module/filesystem]
type = internal/fs
interval = 10

mount-0 = /

format-mounted                      =   <label-mounted>
format-mounted-prefix               =   ""
format-mounted-prefix-background    =   ${colors.cyan}
format-mounted-prefix-foreground    =   ${colors.bg}
format-mounted-prefix-padding       =   1
format-mounted-underline            =   ${colors.cyan}

label-mounted                       =   %{T1}%percentage_used%%%{T-}
label-mounted-background            =   ${colors.bg-light}
label-mounted-foreground            =   ${colors.fg}
label-mounted-padding               =   1

format-unmounted                    =   <label-unmounted>
format-unmounted-prefix             =   ""
format-unmounted-prefix-background  =   ${colors.red}
format-unmounted-prefix-foreground  =   ${colors.bg}
format-unmounted-prefix-padding     =   1
format-unmounted-underline          =   ${colors.red}

label-unmounted                     =   %{T1}unmounted%{T-}
label-unmounted-background          =   ${colors.bg-light}
label-unmounted-foreground          =   ${colors.fg}
label-unmounted-padding             =   1

[module/memory]
type        =   internal/memory
interval    =   1

format-prefix               =   ""
format-prefix-background    =   ${colors.pink}
format-prefix-foreground    =   ${colors.bg}
format-prefix-padding       =   1
format-underline            =   ${colors.pink}

label               =   %{T1}%percentage_used%%%{T-}
label-background    =   ${colors.bg-light}
label-foreground    =   ${colors.fg}
label-padding       =   1

[module/cpu]
type        =   internal/cpu
interval    =   1

format-prefix               =   ""
format-prefix-background    =   ${colors.purple}
format-prefix-foreground    =   ${colors.bg}
format-prefix-padding       =   1
format-underline            =   ${colors.purple}

label               =   %{T5}%percentage:2%%%{T-}
label-background    =   ${colors.bg-light}
label-foreground    =   ${colors.fg}
label-padding       =   1

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98

format-charging                     =   <label-charging>
format-charging-prefix              =   ""
format-charging-prefix-background   =   ${colors.cyan}
format-charging-prefix-foreground   =   ${colors.bg}
format-charging-prefix-padding      =   1
format-charging-underline           =   ${colors.cyan}

label-charging              =   %{T1}%percentage%%%{T-}
label-charging-background   =   ${colors.bg-light}
label-charging-padding      =   1

format-discharging                      =   <label-discharging>
format-discharging-prefix               =   ""
format-discharging-prefix-background    =   ${colors.cyan}
format-discharging-prefix-foreground    =   ${colors.bg}
format-discharging-prefix-padding       =   1
format-discharging-underline            =   ${colors.cyan}

label-discharging               =   %{T1}%percentage%%%{T-}
label-discharging-background    =   ${colors.bg-light}
label-discharging-padding       =   1

format-full                     =   <label-full>
format-full-prefix              =   ""
format-full-prefix-background   =   ${colors.cyan}
format-full-prefix-foreground   =   ${colors.bg}
format-full-prefix-padding      =   1
format-full-underline           =   ${colors.cyan}

label-full              =   %{T1}%percentage%%%{T-}
label-full-background   =   ${colors.bg-light}
label-full-padding      =   1

[module/session]
type = custom/text

click-left = lxsession-logout -p ""
content-prefix = "襤"
content-prefix-background   =   ${colors.red}
content-prefix-foreground   =   ${colors.bg}
content-prefix-padding      =   1
content-underline           =   ${colors.red}

content = %{T1} Session %{T-}
content-background = ${colors.bg-light}
content-foreground = ${colors.fg}

[module/margin]
type = custom/text

content = %{T2} %{T-}
content-foreground = ${colors.trans}
